name: Snyk Container Security

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  snyk-container-security:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Snyk CLI for Container Security
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t your/image-to-test .

      # Run Snyk Container security scan
      - name: Snyk Container monitor
        run: snyk container monitor your/image-to-test --file=Dockerfile || true
