name: Snyk Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 18 * * 4'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Step to build Docker image
      - name: Build a Docker image
        run: docker build -t your/image-to-test .

      # Step to validate SNYK_TOKEN
      - name: Validate SNYK_TOKEN
        run: |
          if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "SNYK_TOKEN is not set"
            exit 1
          else
            echo "SNYK_TOKEN is set"
          fi

      # Step to run Snyk to check Docker image for vulnerabilities
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: your/image-to-test
          args: --file=Dockerfile

      # Step to upload results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
