name: Snyk Code Analysis (SAST)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  snyk-sast:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Snyk CLI for SAST (Snyk Code)
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Code analysis for SAST
      - name: Snyk Code test (SAST)
        run: snyk code test --sarif > snyk-code.sarif || true

      # Upload SARIF report for GitHub Security Tab
      - name: Upload Snyk Code results to GitHub Security Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
