name: Snyk SAST Scan

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  snyk-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Snyk SAST Scan
        uses: snyk/actions/node@master # Use 'node' for Node.js projects
        with:
          args: code test --severity-threshold=high --all-projects  # Snyk Code for SAST
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} #Snyk Token
