name: Snyk Open Source Analysis (SCA)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  snyk-sca:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Snyk CLI for SCA
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Open Source analysis
      - name: Snyk Open Source monitor (SCA)
        run: snyk monitor --all-projects || true
