name: Snyk SCA Dependency Scan

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  snyk-sca-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Latest stable version

      - name: Snyk SCA Dependency Scan
        uses: snyk/actions/node@master  # Use 'node' for Node.js projects
        with:
          args: test --severity-threshold=high --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Store token in Secrets
